services:
  astro-blog-portofolio:
    build: 
      context: ../
      dockerfile: docker/dockerfile
    ports:
      - "4321:4321"
    depends_on:
      astro-blog-db:
        condition: service_healthy
    networks:
      - pgdata-astro

  astro-blog-db:
    image: postgres
    environment:
      POSTGRES_USER: astro
      POSTGRES_PASSWORD: root
      POSTGRES_DB: astro
    ports:
      - "54354:5432"
    volumes:
      - pgdata-astro:/var/lib/postgresql/data
    networks:
      - pgdata-astro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U astro"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata-astro:

networks:
  pgdata-astro:
  

    